# title of website
title: HANGZHOU 0571.info

# description of website
description: byang0571's navigation site

# favicon of website
favicon: "https://github.com/byang0571.png?size=40"

# your website url
url: https://byang0571.github.io/0571.info/

# github profile url
github: "https://github.com/byang0571"

# footer message
footer: © 2023-2023 0571.info design by Byang

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: ""

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:     
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 片库
          description: 主看片子的地方
          url: https://pian-ku.com/
        - name: 海外影视
          description: 备用看片子的地方一
          url: https://hwaitv.com/
        - name: BTNull
          description: 备用看片子的地方二
          url: https://www.btnull.to/
        - name: Youtube(科学上网)
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google(科学上网)
          description: 全球最大的搜索平台
          url: https://www.google.com/
        - name: Excalidraw
          description: 流程图工具，可以画手写风格图表
          url: https://excalidraw.com/
    - name: 好好学习
      sites:
        - name: TED
          description: 值得传播的创意
          url: https://www.ted.com/
        - name: Elllo
          description: 英语听力在线实验室
          url: https://elllo.org/
    - name: 在线工具
      sites:
        - name: 纪妖
          description: 收集中国古今妖怪
          url: https://www.cbaigui.com/
        - name: PixFix
          description: 修复图片的神奇网站
          url: https://zh.pixfix.com/
        - name: RemoveBG
          description: 在线抠图平台-高清
          url: https://www.remove.bg/
        - name: Magic-Eraser
          description: 在线编辑图片平台
          url: https://magicstudio.com/
        - name: TinyPNG
          description: 在线图片压缩平台
          url: https://tinypng.com/
        - name: Extractor Image
          description: 一键下载网站图片
          url: https://extract.pics/
        - name: RoomGPT
          description: 在线装修AI设计平台
          url: https://www.roomgpt.io/
        - name: Vega AI
          description: 在线AI绘画平台
          url: https://rightbrain.art/
        - name: TinyWow
          description: 在线格式转换平台
          url: https://tinywow.com/
        - name: 简视频
          description: 一个网站搞定视频制作
          url: https://www.aewz.com/
        - name: YMAL
          description: 在线验证YAML代码
          url: https://www.yamllint.com/
    - name: 休闲游戏
      sites:
        - name: 小霸王
          description: 在线小霸王游戏机，支持多人联机
          url: https://www.yikm.net/
        - name: 扫雷
          description: 网页版扫雷，开箱即用
          url: http://www.cctvjs.net/mine/
        - name: 连连看
          description: 网页版连连看，开箱即用
          url: http://www.cctvjs.net/link/
        - name: 俄罗斯方块
          description: 网页版俄罗斯方块，开箱即用
          url: http://www.cctvjs.net/tetris/
        - name: 贪吃蛇
          description: 网页版贪吃蛇，开箱即用
          url: http://www.cctvjs.net/snake/
